### ISSUE TITLE
Mod doesn't work on my modpack

### ISSUE THREAD

**Issue by Kablumbaa** [EtherealEmil/UsualScrap#1]
There are no items in the shop to buy 

[Info   :   BepInEx] Loading [UsualScrap 1.3.6]
[Error  : Unity Log] TypeLoadException: Could not load list of method overrides due to Method not found: bool .IHittable.Hit(int,UnityEngine.Vector3,GameNetcodeStuff.PlayerControllerB,bool)
Stack trace:
System.RuntimeType.GetMethodsByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.RuntimeType+MemberListType listType, System.RuntimeType reflectedType) (at <787acc3c9a4c471ba7d971300105af24>:IL_001B)
System.RuntimeType.GetMethodCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.CallingConventions callConv, System.Type[] types, System.Int32 genericParamCount, System.Boolean allowPrefixLookup) (at <787acc3c9a4c471ba7d971300105af24>:IL_0010)
System.RuntimeType.GetMethods (System.Reflection.BindingFlags bindingAttr) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
UsualScrap.Plugin.NetcodePatcher () (at <d33666b729914292ae8c5978f42977cc>:IL_0018)
UsualScrap.Plugin.Awake () (at <d33666b729914292ae8c5978f42977cc>:IL_0001)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

edit: sorry forgot to paste the error log

**Comment by EtherealEmil** [comment]
Could you post a link to the modpack?

**Comment by EtherealEmil** [comment]
It's v50 issues. I'll see what I can do.

**Comment by EtherealEmil** [comment]
This issue is fixed in the new version I just posted and the shop items should now show up. I'll leave this open for a while just in case.

**Comment by Teacyn** [comment]
Confirming that it appears to work fine on v50 now on my end.

**Comment by EtherealEmil** [comment]
Great, I will close this then. Thank you both for the help.
