### ISSUE TITLE
[UsualScrap v1.4.7] [Lethal Company V55]

### ISSUE THREAD

**Issue by PeacemakerSofanthiel** [EtherealEmil/UsualScrap#16]
Dropping the padlock adds 104 lbs to the player that can only be removed by relogging.

**Comment by EtherealEmil** [comment]
Haven’t had a chance to test anything in v55 but I’ll take a look when I can.

**Comment by Skyblade799** [comment]
Had the same issue. It's probably the same issue the other mods are having. Lethal Casino as well as some others had issues with their items dropping to 100 pounds in v56.

**Comment by EtherealEmil** [comment]
Turns out this was my bad, it just didn't cause issues until v55 changed some things internally. It was a simple fix and is no longer a problem in the latest version! Thanks for the report, I will close this shortly.
