### ISSUE TITLE
Custom config?

### ISSUE THREAD

**Issue by DatBoi302** [EtherealEmil/UsualScrap#20]
Does the mod not come with an editable .cfg file? One that would allow us to turn certain items on/off, custom pricing, effects, etc.
Sorry if its there and I somehow missed it, booted the game up with the mod installed, then exited, but not config to be found. Let me know if its something on my end or if its not, if you'll be planning on adding one.
Thanks!

**Comment by EtherealEmil** [comment]
There is no config options in any versions currently so that is not an issue on your end. I will be adding some configs either in the next update which will be a bug fix update or the update after that which will add new stuff. I plan to post those updates next week when I'll finally have time to work on the mod.

**Comment by DatBoi302** [comment]
Awesome, no rush. I currently have your mod installed, but disabled. Only reason is because there is an item or two we'd like to remove/slash edit, such as the _medkit_ (its already in another mod we use).

As far as custom config stuff we'd like, pretty much just the basics.
- Enable / Disable each piece of equipment / scrap from being able to spawn or be purchased
- The price for each piece of equipment

However, if you do end up adding more stuff it be cool to see some config lines for:
- Editing more in-depth details for items and scrap, for instance how bright the _handlamp_ is, damage the crowbar does, explosive tank timer length or the ability to disable the timer. Like that kind of stuff.
- Weight and value of scrap
- Names for items, allowing us to change the to our own custom names, this could help with overlaps like in the instance of two mods both adding items in the store called "medkit", being able to change the "toolbox" to "tools". Blah blah blah, I think you get the idea!

Thanks for the support.

**Comment by EtherealEmil** [comment]
Some configs have been added and name schemes have changed to prevent conflicts with other mod's items, enjoy! I have taken note of your other suggestions and will close this issue soon, thanks.
