### ISSUE TITLE
Store items have scan nodes

### ISSUE THREAD

**Issue by Ryyye** [EtherealEmil/UsualScrap#21]
The tools in the store have scan nodes unlike vanilla tools, which also causes them to have 2 scan nodes if a mod is installed that adds nodes to tools

**Comment by EtherealEmil** [comment]
This isn't really an issue as much as it is a design choice, all of my items have scan nodes and I wouldn't be able to tie that to a config so it's just an unfortunate mod conflict. The padlock for example needs a scan node as it can be a scrap item but it can also be a store item so it'd always have issues with that mod.

**Comment by Ryyye** [comment]
That's valid if you want them to be built into the mod, just a suggestion, but maybe items that are exclusively from the store could have blue scan nodes?

**Comment by EtherealEmil** [comment]
I could maybe do that but what would that solve? There would still be duplicate scan nodes with that mod you've mentioned it's just that one would now be blue.

**Comment by Ryyye** [comment]
The tool scan nodes (as well as the interactables in the ship) are blue, and the items from this could be blacklisted from getting an additional node (via that mod's config).
Realistically though, it's pretty inconsequential, so I understand not changing it too.
