### ISSUE TITLE
Modded compat for toolbox

### ISSUE THREAD

**Issue by Ryyye** [EtherealEmil/UsualScrap#22]
Unsure how feasible this is, but compatibility for modded hazards with the toolbox would be nice if it's easily doable (specifically sea mines from Surfaced and missile turrets from the mod by the same name)

**Comment by EtherealEmil** [comment]
I'll take a look around, I haven't added integrations with any mods yet but it's definitely possible, it's just a question of how convoluted it would be.

**Comment by EtherealEmil** [comment]
So I can do this either very meticulously by adding integration with each mod's traps or I can just have one function for all traps my mod doesn't recognize; both ways have their pros and cons. Either way this functionality will be added.

**Comment by EtherealEmil** [comment]
After trying to implement this and breaking the game several times, I realized it's a bit harder and I'll have to add direct compatibility with each mod. May happen eventually but it'll be a learning moment for me.

**Comment by EtherealEmil** [comment]
Toolbox will be redone next update so I will close this as it MAY no longer be relevant. Sorry I didn't manage to accomplish this.
