### ISSUE TITLE
Additional config for toolboxes

### ISSUE THREAD

**Issue by Ryyye** [EtherealEmil/UsualScrap#23]
If it's easily possible, config options for the amount of scrap you get from disabling hazards, as well as the time it takes, would be nice

**Comment by EtherealEmil** [comment]
Not easily done as far as I know but I don't know much so maybe when I have time to spare. If you have some ideas to better balance those values so it's more enjoyable I'm all ears. The current values weren't tested much but I wanted to get the update out so I settled with them.

**Comment by Ryyye** [comment]
Makes sense, I think the current values could be a bit lower, I'd personally let the toolbox just turn traps into either 1 metal sheet or 1 big bolt, since it'd make it more of a long-term investment. Although I've only played with the toolbox a bit.

**Comment by EtherealEmil** [comment]
I've reduced some values in my latest unreleased version after having some free time to playtest so you may see that release sometime soon. As for the configs request, I will add more configs every once in a while and will take note that you've asked for these config options but I can't say when I'll get to adding them.

**Comment by Ryyye** [comment]
Of course, I appreciate your consideration regardless

**Comment by Xeraccoon** [comment]
being able to choose the deactivation time of the turrets, mine, see being able to deactivate the fact of being able to destroy the turrets because I find that strong personally
