### ISSUE TITLE
[Request] Price/carry weight config for the scrap?

### ISSUE THREAD

**Issue by Ryyye** [EtherealEmil/UsualScrap#27]
Usually I'm able to finetune the prices of scrap through another mod, but it seems like this mod's scrap prices are unaffected for some reason.

**Comment by EtherealEmil** [comment]
Finetune the prices using what mod?

**Comment by Ryyye** [comment]
No worries, I use itemweights. It seems to update the weights fine (?), but for some reason doesn't affect prices of items from this mod.

**Comment by EtherealEmil** [comment]
If I was to guess I say it's because I don't set the price the normal way in unity and I set them through lethallib code. That mod either doesn't target the lethallib method or my mod is loading after that mod and is overwriting it.

**Comment by EtherealEmil** [comment]
This has been finally added, thank you for waiting so long. I will close this issue now.
