### ISSUE TITLE
Balance défibrilator

### ISSUE THREAD

**Issue by Xeraccoon** [EtherealEmil/UsualScrap#28]
Hi, I don't know if you planned it or if you didn't think about it, but it would be nice to be able to configure the number of possible resuscitations per mission (the session inner when you arrive on a moon and leave).

if possible adapt to MoreCompany (personally I often play with 4/6 players).

example of configuration: 4 players

0.5 = 2 rez
1 = 4 rez
2 = 8 rez

if you can give feedback on the outcome if it is validated or rejected, that would be very cool thanks in advance

**Comment by EtherealEmil** [comment]
I will think about it, I don't know if the game itself gives me access to how it tracks the days or if I'd have to write a large chunk of code to do it. Only answer I can currently give is I'll look into it and get back to you.

**Comment by Xeraccoon** [comment]
It works thanks for the answer ^^

**Comment by EtherealEmil** [comment]
I didn't decide to go the route of revives per day as it's a bit confusing to implement so I will close this but thanks for the suggestions.
