### ISSUE TITLE
Option disable turret destruction by toolbox

### ISSUE THREAD

**Issue by Xeraccoon** [EtherealEmil/UsualScrap#29]
An option to disable turret destruction using a toolbox would be nice, because I personally find it too strong

**Comment by EtherealEmil** [comment]
Seeing as that is best use for the toolbox I can't see myself adding this as a config. Only thing I would do is make it require that the trap is disabled like it was originally so it requires a ship player and toolbox user to work together.
Sorry.

**Comment by Xeraccoon** [comment]
a toolbox for mines and one for turrets otherwise? personally I deactivated it as a result, because breaking the turrets with a box bought in the shop is too strong, ultimately if it was in drop at a low rate it would be ok, after that I still use the mod for the objects to be sell and some have nice and fair play effects.
