### ISSUE TITLE
defibrilator doesnt work/nerf/buff idea

### ISSUE THREAD

**Issue by pizzalover99** [EtherealEmil/UsualScrap#33]
hello, i was excited to try out the new items as i am always, but somehow the defibrilator wasnt working sadly, i tried left clicking holding left click, spamming nothing worked. id like for it to be fixed and for it to be a little bit morebalanced perhaps? my input would be to make it more expensive, and also limit where it can be used, i suggest 1 charge reviving one guy but he can be on critical health or less than 100, that way you arent able to revive 100 health out of the get go ( maybe this could work if the defib had 2 charges) and another nerf to it would be for example, you cannot revive players killed by coil heads, cannot revive scorched players (oldbird grab), cannot revive snipped players (barber) you could add more of course but yeah. its a really interesting item and this is my contribution to makiing more fun/balanced. but yeah currently it doesnt work and i wasnt able to find anything in the config to enable it to work. thank you!

**Comment by EtherealEmil** [comment]
The defib is a new item and therefore may take a bit before I get it working 100%, with that being said I was pretty tired and made some simple mistakes while coding it that I have since fixed. I really like your balance ideas/changes and am happy to implement some of them after I get it working smoothly first. I would personally disable it for now as it will not be very balanced but after a few updates I should get it in a good spot balance wise. Thanks! If you'd like credit for the changes/ideas in the changelogs let me know.

**Comment by pizzalover99** [comment]
hey thank you so much for your reply, i see now well i hope you get to fix it im really having fun with the mod its really briliant,  oh and also maybe you could also add cocooned players to that list of unrevivables haha, i also had one more change maybe, maybe youd need to use it a couple times for it to work since normal defibs can take multiple tries to revive a patient, kinda like the cruiser ignition(so if you decide to add this maybe the defib could use extra charge bars like 3 or 4 so  you can either be super lucky and revive a player on the first hit or  be unlucky and use all charges to revive, if ur lucky u get to revive more players with the extra charges which sounds fun), defib could also use some sounds (of course not need to add this if you find it difficult) oh and also it would be so nice to give some particles effects/sfx to the lifeline, its a cool item but its silent, it also seems somewhat really good in my opinion? being able to grab loot with it and beign able to save yourself from danger or falls, maybe it needs an extra risk? thats just me though, anyways id love to see more updates yorue doing really good work and no need to credit me of course, youre the master mind im just here to give my input its the least i can do:D

**Comment by EtherealEmil** [comment]
I'm fairly sure I can't differentiate the methods that players have died in code very well but I'll see what I can do, the other ideas sound good after I get it working. Sounds and effects are being added, I'm just picky so it take a while to find the perfect ones I want.

**Comment by pizzalover99** [comment]
awesome sauce, thank you

**Comment by lethally** [comment]
sigma, i think ima go try this revive thing now

**Comment by EtherealEmil** [comment]
This is fixed/implemented and will release in a day or so, so I'm going to close this.

**Comment by NTBBloodbath** [comment]
Hey, sorry for reviving this closed issue but do you have any idea what could be wrong with the defibrillator? I updated to the latest version and the logs say "no corpse found" when trying to use it, no matters what. Is there a way to make the mod spit out some more logs that could be useful for debugging?

Cheers

**Comment by EtherealEmil** [comment]
It just doesn't work at all in the most recent released version. But luckily I have 100% fixed it and tested it in my next version so keep an eye out for that. Right now I'm just trying to polish the update while I still have time.
