### ISSUE TITLE
Candy dispenser allows you to duplicate candy on the ship.

### ISSUE THREAD

**Issue by Croft3r** [EtherealEmil/UsualScrap#41]
When using the candy dispenser inside the ship, while in space, the dispenser will spawn candy which can be sold. A good solution to that issue would be to decline dropping candy if the hit was against a player or if the ship is in space.

Thanks! Having a lot of fun with this mod.

**Comment by EtherealEmil** [comment]
Think I may add a cap on how many candies can be spawned per planet and disable it while in space. It will be changed soon.

**Comment by pizzalover99** [comment]
hello i may have a better rework, random chance to spawn candy 1-4 chance or 1 in 3 or 1 in 5 eachtime you actually hit an entity, rewarding you for using it in combat, or rewards you with one candy each kill, but then again it does x2 damage which is rlly good, so yeah, maybe making it rarer would balance it or buffing candy prices OR renabling those 3 candies to only drop from candy dispenser

**Comment by EtherealEmil** [comment]
This is fixed/implemented and will release in a day or so, so I'm going to close this.
