### ISSUE TITLE
Injector bug + some feedback

### ISSUE THREAD

**Issue by SleepyMiles** [EtherealEmil/UsualScrap#45]
The injector drains stamina immediately after use. From my understanding, this should happen only after the buff duration ends (1 min)

Feedback
It would be good if the stamina color change were compatible with the EladsHud mod, but I think it's not as easy as it sounds.

https://github.com/user-attachments/assets/12e9f67c-6a43-4284-beee-ad6026781add

**Comment by EtherealEmil** [comment]
Your sprint being drained was an accident, I left a line of code that drained it for some reason. Will be fixed next update. As for compatibility with other huds I don't even know where to start trying to do that, what I will say is if I ever figure out how to just make a custom screen effect the bar changing colors will be replaced by that and thus won't need any compatibility stuff.
