### ISSUE TITLE
Store items not showing up

### ISSUE THREAD

**Issue by deerbuster** [EtherealEmil/UsualScrap#46]
Have HookGenPatcher, BepInExPack, LethalLib, UsualScrap, Helmet_Cameras LateCompany ReservedItemSlotCore ReservedFlashlightSlot ReservedWalkieSlot , but even without the other mods, store items never appeared, while other mods appear to work fine.  Installed and launched via Thunderstore.  All current versions.

**Comment by EtherealEmil** [comment]
It worked fine when I tested and others have been using it fine so I don't know why it isn't working for you. Some causes I could think of are that the mod isn't being loaded at all for some reason which you can test using a mod that lets you spawn items or looking for "usual scrap loaded!" in the console or the other idea is that your configs for the mod could be messed up and all the items are disabled.

**Comment by deerbuster** [comment]
[Log.zip](https://github.com/user-attachments/files/17199361/Log.zip)
Here is my log for it

**Comment by EtherealEmil** [comment]
Just had a friend check and it is confirmed working fine. I checked the log and it did say it loaded but there may be other errors causing issues. Here are some steps that may fix your issue.

- Do a clean install of lethal company and verify your files via steam.
- If you changed versions of lethal company make sure you run the vanilla game once before trying to play modded.
- Could be a thunderstore issue you can also try R2modman as that may work better or just a reinstall of thunderstore.
- Check the bepinex/config folder and make sure there aren't duplicate UsualScrap configs and neither have items being loaded set to disabled or are unregistered.
- And lastly double check everything is up to date.
- If you're using a mac maybe that could be the issue? A pirated version of the game is an issue.

That's everything I know and I wish you luck trying to fix your issue. Sorry I can't really help you any further.

**Comment by deerbuster** [comment]
:( I just tried it with r2, same issue.  I assume that the items are in the store by default and there is nothing additional I have to do to get them in there?

**Comment by EtherealEmil** [comment]
Shouldn't be anything other than your configs which should already have everything enabled.
