### ISSUE TITLE
Jump Glitch - Frigid Capsule

### ISSUE THREAD

**Issue by joeymintz564** [EtherealEmil/UsualScrap#48]
Playing with a couple other mods in a lobby of 5 players (morecompany), all players in the lobby who were frozen by the frozen capsule could no longer jump. The animation would proceed, however, the model would jump maybe 1 or 2 pixels length. This was using the 1.7 version of UsualScrap.

**Comment by EtherealEmil** [comment]
Already working on it, freezing will be removed and replaced by something else as it's not to interesting and causes issues.
