### ISSUE TITLE
Handlamp Command Conflict

### ISSUE THREAD

**Issue by Nystrata** [EtherealEmil/UsualScrap#49]
When used in conjunction with https://thunderstore.io/c/lethal-company/p/Mellowdy/HandheldMap/  
Typing in `hand-held map` into the terminal to buy it instead prompts for buying the handheld lamp instead, even when `handlamp is loaded` and `handlamp is a store item` are both set to false
Is there a way to make the command matching for it less aggressive?

**Comment by EtherealEmil** [comment]
There was a mod called terminal command fixes or something like that. That will fix it. I don't know why the terminal is so blunt in vanilla. I may change the name a bit but we'll see.

**Comment by Nystrata** [comment]
Ah, yeah, if it's a vanilla bug, it can't be helped   
Thank you for the suggestion,. I'll give it a a try!

**Comment by EtherealEmil** [comment]
I'm glad, hope you enjoy.
