### ISSUE TITLE
Way to disable icons?

### ISSUE THREAD

**Issue by Lincolnium** [EtherealEmil/UsualScrap#50]
I was wondering if you could add a config to remove item icons, because I’m using the Runtime Icons mod and I’d like the scrap from this mod to look like other icons from the mod, and same with the equipment

**Comment by EtherealEmil** [comment]
Wouldn't it make more sense to ask them for a config to override all item icons? Adding a config to remove my icons would be a lot of work for a very specific issue, if even possible. My icons are set in unity and not in code so I'd have to figure out how to reference each individual item's icons and etc..

**Comment by EtherealEmil** [comment]
I was referring to asking the author of runtime icons to make an override all icons config. Anyways, sorry.
